---
name: Build Debian Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Debian Package
        uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: -b -rfakeroot -us -uc
          extra-build-deps: dkms

      - name: Upload Debian Package
        uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: debian/artifacts
